/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combos': typeof CombosRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/combos'
    | '/contact'
    | '/courses'
    | '/faculty'
    | '/gallery'
    | '/shop'
    | '/courses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/combos'
    | '/contact'
    | '/courses'
    | '/faculty'
    | '/gallery'
    | '/shop'
    | '/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/combos'
    | '/contact'
    | '/courses'
    | '/faculty'
    | '/gallery'
    | '/shop'
    | '/courses/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombosRoute: typeof CombosRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  FacultyRoute: typeof FacultyRoute
  GalleryRoute: typeof GalleryRoute
  ShopRoute: typeof ShopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombosRoute: CombosRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  ShopRoute: ShopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
